spring:
        profiles:
                active: dev
---
spring:
        profiles: dev
        datasource:
                driverClassName: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/mypage
                username: postgres
                password: kobayashi
---
spring:
        profiles: test
        datasource:
                driverClassName: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/mypage
                username: postgres
                password: kobayashi

